require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - '.pryrc'
    - 'bin/rails'

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 80

# DISABLED because subclasses can define properties/attributes and then call the
# superclass constructor
Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false

Metrics:
  Enabled: true

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

# Permit certain names that are less than three characters long, but which make
# sense to have as valid parameter names.
Naming/MethodParameterName:
  AllowedNames:
    - 'as'
    - 'by'
    - 'id'
    - 'if'
    - 'ip'
    - 'to'
    - 'x'
    - 'y'
