require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '.pryrc'
    - 'bin/rails'

Metrics:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

# Permit certain names that are less than three characters long, but which make
# sense to have as valid parameter names.
Naming/MethodParameterName:
  AllowedNames:
    - 'as'
    - 'by'
    - 'id'
    - 'if'
    - 'ip'
    - 'to'
    - 'x'
    - 'y'
